# Generated by Django 2.2.3 on 2020-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('gender', models.CharField(max_length=10, verbose_name='gender')),
                ('fees', models.FloatField(verbose_name='fees')),
                ('address', models.TextField(max_length=100, verbose_name='address')),
                ('active', models.CharField(default='Y', max_length=10, verbose_name='isactive')),
            ],
        ),
    ]
