# Generated by Django 2.2.5 on 2020-02-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.CharField(default='Y', max_length=1, verbose_name='active'),
        ),
    ]
